name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e_test:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the stack
      working-directory: ./tests
      run: docker-compose up -d

    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: http://127.0.0.1:8088/metrics|http://127.0.0.1:8087/metrics|http://127.0.0.1:8089/metrics
        # Fail this action after this many failed attempts
        max-attempts: 5
        # Delay between retries
        retry-delay: 5s
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: true

    - name: Download dataset
      run: wget https://cdn.gorse.io/example/github.sql

    - name: Import dataset
      run: mysql -h 127.0.0.1 -u gorse -pgorse_pass gorse < github.sql
